### ISSUE TITLE
Unhandled Exception when connection is lost

### ISSUE THREAD

**Issue by vincent-iQontrol** [shamblett/coap#153]
When I try to read multiple data when the connection is lost, for example I shut off the wifi after there was a connection there is a unhandled exception. This only occur when I try to read multiple things. For example dummy code:

await read('x'); caught error > CoapRequestTimeoutException: Request timed out after 1 retransmits.
await read('y'); > Unhandled Exception: Bad state: Future already completed

// read function
read(String name)
try {
      var response = await _client.put('Json', payload: payload)

I also use openssl.

**Comment by JKRhb** [comment]
Does this also occur with the current state of #149 and/or with regular `coap://` requests?

**Comment by vincent-iQontrol** [comment]
@JKRhb I use the regular Release 7.0.0 version. I use openssl the schema is coaps.

**Comment by vincent-iQontrol** [comment]
@JKRhb thank you for your reply. I'm not sure what to test. The issue is already merged in _shamblett:master_ right?

**Comment by JKRhb** [comment]
> The issue is already merged in _shamblett:master_ right?

Exactly, so you would need to replace the `7.0.0` dependency with one pointing to the Git repository. I think this should work:

```yaml
  coap:
    git:
      url: https://github.com/shamblett/coap.git
```

**Comment by vincent-iQontrol** [comment]
@JKRhb It look like the exception from the second request is now catched, but still after the second try it comes with: 
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Future already completed

[log] CONNECTION: read value 10.0.10.56
[log] CONNECTION: read error: CoapRequestTimeoutException: Request timed out after 1 retransmits.

[log] CONNECTION: read value 10.0.10.56
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Future already completed
#0      _Completer.completeError (dart:async/future_impl.dart:15:31)
#1      _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
#2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#4      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#5      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#6      _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#7      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#8      _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
#9      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#10     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#11     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#12     _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:392:20)
#13     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
#14     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:391:5)
#15     _AsBroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:486:5)
#16     _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
#17     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#18     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#19     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#20     _SyncStreamControllerDispatch._sendError (dart:async/stream_controller.dart:778:19)
#21     _StreamController._addError (dart:async/stream_controller.dart:656:7)
#22     _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
#23     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#24     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#25     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#26     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#27     _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#28     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#29     _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
#30     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#31     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#32     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
#33     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#34     _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#35     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#36     _RootZone.runBinaryGuarded (dart:async/zone.dart:1598:10)
#37     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
#38     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:376:7)
#39     _DelayedError.perform (dart:async/stream_impl.dart:526:14)
#40     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#41     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
[log] CONNECTION: read error: CoapRequestTimeoutException: Request timed out after 1 retransmits.
[VERBOSE-2:profiler_metrics_ios.mm(203)] Error retrieving thread information: (os/kern) invalid argument`

[log] CONNECTION: read error: CoapRequestTimeoutException: Request timed out after 1 retransmits.

**Comment by vincent-iQontrol** [comment]
I wil try to digg deeper monday. Thanks.

**Comment by JKRhb** [comment]
You're welcome! Feel free to also try out the version from my fork, like so:

```
  coap:
    git:
      url: https://github.com/namib-project/coap.git
      ref: openssl-psk
```

**Comment by vincent-iQontrol** [comment]
> 
@JKRhb I can only test openssl with certificates. When you include this feature I will test it. Thank you.

**Comment by vincent-iQontrol** [comment]
I still get the `Unhandled Exception: Bad state: Future already completed` when connection is lost. I think something has to drain when connection is lost or something.

**Comment by JKRhb** [comment]
> I still get the `Unhandled Exception: Bad state: Future already completed` when connection is lost. I think something has to drain when connection is lost or something.

Thank you for the update! I will also try to have a look into this

**Comment by JKRhb** [comment]
Hmm, have you been able to determine where the exception is being thrown? I wonder if it's in the `_waitForResponse` or `_waitForReject` methods (where a Completer is being used) or in an actual stream?

**Comment by vincent-iQontrol** [comment]
@JKRhb I have added some prints through the code and it looks like it is in the waitforResponse.

**Comment by JKRhb** [comment]
Thank you for investigating! I suppose the error is added to the stream here, causing the completer to complete with an error:

https://github.com/shamblett/coap/blob/d069d527458dddb2278ebcef11f6c0da557c686e/lib/src/coap_client.dart#L694-L698

Then, after the reconnection, the completer completes again with the response, causing the StateError. I guess we need to adjust the behavior for the reconnection case somehow.

**Comment by JKRhb** [comment]
Hmm, maybe we can simply a check for `completer.isCompleted` to the `_waitForResponse` method?

**Comment by JKRhb** [comment]
Could you try out the changes from this patch for example?

```diff
--- a/lib/src/coap_client.dart
+++ b/lib/src/coap_client.dart
@@ -647,10 +647,20 @@ class CoapClient {
     final completer = Completer<CoapResponse>();
     responseStream.take(1).listen(
       (final response) {
+        if (completer.isCompleted) {
+          return;
+        }
+
         response.timestamp = DateTime.now();
         completer.complete(response);
       },
-      onError: completer.completeError,
+      // ignore: avoid_types_on_closure_parameters
+      onError: (final Object error) {
+        if (completer.isCompleted) {
+          return;
+        }
+        completer.completeError(error);
+      },
     );
     return completer.future;
   }
```
