### ISSUE TITLE
Observing resources does not work anymore

### ISSUE THREAD

**Issue by JKRhb** [shamblett/coap#190]
If I am not mistaken, the client's `observe` method does not work as expected anymore and emits only the response to the initial registration request while ignoring any subsequent responses. This behavior can be observed[^1] when running the `get_observe_async` example.

[^1]: No pun intended ;)

**Comment by shamblett** [comment]
Agreed, well spotted.

**Comment by shamblett** [comment]
Confirmed this working now, thanks.

**Comment by JKRhb** [comment]
> Confirmed this working now, thanks.

Thank you :) Would it be possible for you to create a new patch release with the changes?

**Comment by shamblett** [comment]
Done, package re released at version 9.0.4
