### ISSUE TITLE
First response from observe not being handled by the onData function passed as argument

### ISSUE THREAD

**Issue by jorgesanfz** [shamblett/coap#193]
In the observe method, the check for the observe flag within the `CoapResponse` involves awaiting `_waitForResponse`. This delays the return of the `CoapObserveClientRelation` object until after the first response is received. As a result, the `CoapObserveClientRelation` object does not yet have the `onData` function passed as an argument, and the first response cannot be handled.

**Comment by shamblett** [comment]
Thanks, looks OK merged.

**Comment by shamblett** [comment]
Package re released at version 9.0.5
