### ISSUE TITLE
DTLS support for coap libary

### ISSUE THREAD

**Issue by sebriede** [shamblett/coap#27]
May it is possible to build up the dtls support fot the coap-client

**Comment by shamblett** [comment]
Maybe, Dart doesn't support DTLS natively, there is no secure socket equivalent for UDP sockets so this would have to be done using FFI but its not impossible, its a fair undertaking though.

**Comment by sebriede** [comment]
Hmm, it sounds not that easy. I just asked because of my Bachelor report, for this it would be practically.
