### ISSUE TITLE
Flutter Project: Could not launch engine with configuration

### ISSUE THREAD

**Issue by pedromassango** [shamblett/coap#3]
After importing this package and I try to run my project (without using any class of the package just importing it), I'm receiving the following error:

`[ERROR:flutter/shell/common/shell.cc(437)] Could not launch engine with configuration.`

### Steps to reproduce

1. add it on `pubspec.yaml`:

```dart
dependencies:
  coap:
```

2. Import it in any file (e.g main.dart):

```dart
import 'package:coap/coap.dart';

void main() {
  runApp(MyApp());
}
```

**Comment by shamblett** [comment]
This is now being tracked  in Issue 4.
