### ISSUE TITLE
Client is unstable

### ISSUE THREAD

**Issue by JosefWN** [shamblett/coap#44]
Hi, great to see a CoAP library for Dart! I decided to try version 3.2.1 out and found some potential issues.

I'm getting intermittent errors:
_Reliability - Retransmission timeout elapsed_
_Reliability - Timeout: retransmit message, failed count: 3 message: 27007_
_Matcher - Ignoring unmatchable piggy-backed response from localhost_

Frequently polling for a resource will yield these failures 5-10% of the time. Both server and client are running on localhost so I think we can rule out issues with the connectivity... Latency on the server side is ~10 ms, CoAP client timeout is 3000 ms with 3 retries. The message size is about 60-120 bytes. Can't see anything indicating an error on the server side.

I'm also getting:
_SEVERE: >> BlockwiseLayer uses MaxMessageSize: 1024 and DefaultBlockSize: 512_

Perhaps this event, which I guess is an info message, doesn't need to be marked as the most severe event of them all in the logs?

**Comment by shamblett** [comment]
OK, so what server are you using?

You say 'Frequently polling for a resource...'  please post the code on how you are doing this.

**Comment by JosefWN** [comment]
Sorry, I've since dug deeper and found issues on the server side, where I'm using https://github.com/plgd-dev/go-coap.

Closing this for now.
