### ISSUE TITLE
[question] Sending a request from the coap_client

### ISSUE THREAD

**Issue by pedromassango** [shamblett/coap#6]
The send function from the `coap_client` class is not using the returned value from the prepape method, it hat right?

In the `coap_client` file we have this: 

```dart
  /// Send
  Future<CoapResponse> send(CoapRequest request) async {
    await prepare(request);
    return request.send().waitForResponse(timeout);
  }
```

Here the `prepare(request)` return a `CoapRequest`. I'm wondering if we must use the returned request from the prepare function or it is ok that way.

**Comment by pedromassango** [comment]
Cc: @shamblett

**Comment by shamblett** [comment]
Its actually OK but very unclear, the prepare method changes the request itself, it sets defaults, resolves the address and sets the endpoint, at this point the request is ready to be used. You could use the returned one but in this case seeing as we are doing no further preparation we don't need to.

The API documentation could make this clearer, also there may well be a better way to do all this. The coap client class is in many ways just supplies a convenient interface to users who don't want to build their own requests, this could be done  this using builder classes instead.

**Comment by pedromassango** [comment]
Thank you. I think I must close this for now
