### ISSUE TITLE
[question] Why this package does not support secure CoAP?

### ISSUE THREAD

**Issue by pedromassango** [shamblett/coap#7]
The docs state that this package does not support secure CoAP. Can you please explain me why?

I'm asking because I want to know if there is something that I can do to add support for it.

**Comment by shamblett** [comment]
Dart supports both secure sockets and web sockets but not secure datagrams, i.e. [DTLS](https://www.3cx.com/webrtc/dtls/) so you can't implement secure CoAP or any other secure datagram protocol using Dart natively.

What I thought of doing was to use [FFI](https://dart.dev/guides/libraries/c-interop) to wrap DTLS natively and use that, I've used FFI to wrap Intels MRAA library for my IOT stuff(my [mraa](https://github.com/shamblett/mraa) project).

The best way to do this is as a separate package so other packages besides coap can use it however unless there is a great outcry for this I can't see me having any time to do this at the moment.

**Comment by pedromassango** [comment]
So its seems to be a litle work here to be do. Unfortunately I don't have time to learn and implement FFI in dart, the best approach here is to build a native Android app. Thank you @shamblett .
