### ISSUE TITLE
Stricter lint config

### ISSUE THREAD

**Issue by JosefWN** [shamblett/coap#77]
The base/recommended lint config is pretty lenient: https://github.com/dart-lang/lints/blob/main/lib/recommended.yaml

Perhaps we could have a look at the list of additional linter rules and add the ones we like: https://dart.dev/tools/linter-rules

Perhaps this can be revised when Dart 2.17 is released, then the `lints` package will be upgraded from v1.0.1 to v2.0.0 as well.

**Comment by shamblett** [comment]
Package re released at version 4.0.0

**Comment by JosefWN** [comment]
I think this could still be relevant to look into when Dart 2.17 is released in the future :)

**Comment by shamblett** [comment]
OK thanks for the update

**Comment by shamblett** [comment]
Can for me.
