### ISSUE TITLE
Specifying client timeout

### ISSUE THREAD

**Issue by JosefWN** [shamblett/coap#78]
The `client.timeout` overrides the timeout implicitly specified by the config, should we allow this/do we need this? Initial discussion: https://github.com/shamblett/coap/pull/76#discussion_r852652408

I propose just dropping the `client.timeout` and letting the config dictate timeouts. Easier to manage in code and less confusing to the users of the library.

**Comment by shamblett** [comment]
Package re released at version 4.0.0
