### ISSUE TITLE
Remove old example code

### ISSUE THREAD

**Issue by JosefWN** [shamblett/coap#79]
Remove old and deprecated:
- `examples/testserver-example` (duplicate example code, uses CoAP.NET which has not seen active development in ~8 years)
- `examples/flutter_example` (superfluous)

**Comment by JKRhb** [comment]
With #85 merged, I think this issue can be closed, right? :)

**Comment by JosefWN** [comment]
Closing :)

**Comment by shamblett** [comment]
Package re released at version 4.2.0
