### ISSUE TITLE
CoAP not working smoothly in flutter

### ISSUE THREAD

**Issue by anayajoshi** [shamblett/coap#9]
1. CoAP requests stops working after 20-25 requests.
2. any request works only if client.close() statement is removed. otherwise gives error Unhandled Exception: Bad state: Cannot add new events after calling close.
3. While sending requests, it is continuously giving following log output to console : INFO: >> Start Mark-And-Sweep with 0 entries

Please help me to solve these problems.

**Comment by anayajoshi** [comment]
> 1. CoAP requests stops working after 20-25 requests.
> 2. any request works only if client.close() statement is removed. otherwise gives error Unhandled Exception: Bad state: Cannot add new events after calling close.
> 3. While sending requests, it is continuously giving following log output to console : INFO: >> Start Mark-And-Sweep with 0 entries
> 
> Please help me to solve these problems.

Please guide me. I am waiting for reply.

**Comment by shamblett** [comment]
Read issue #8 point 2 above has been seen before and addressed by @joker101.  To disable logging to the console turn off all log levels in the config file. If you continue having problems I'll need a full log output, i.e. turn on all log levels and post the log output.

**Comment by shamblett** [comment]
From #8 -

```
I have tried this for put request. But after, it works for sometime. But after sometime, after about 20-25 requests, the app does not send commands, also the coap server gets hang.
Please guide
```
As I said above I need a full log output of what you are doing to investigate further.

**Comment by anayajoshi** [comment]
> 1. CoAP requests stops working after 20-25 requests.
> 2. any request works only if client.close() statement is removed. otherwise gives error Unhandled Exception: Bad state: Cannot add new events after calling close.
> 3. While sending requests, it is continuously giving following log output to console : INFO: >> Start Mark-And-Sweep with 0 entries
> 
> Please help me to solve these problems.

Launching lib/main.dart on MotoG3 TE in debug mode...
I/flutter (  860): 2020-10-31 10:49:03.851: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.868: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.884: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.902: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.919: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.936: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.953: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.970: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:03.987: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:04.004: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:04.021: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:04.038: INFO: >> Start Mark-And-Sweep with 0 entries
I/flutter (  860): 2020-10-31 10:49:04.054: INFO: >> Start Mark-And-Sweep with 0 entries
Running Gradle task 'assembleDebug'...


I am getting this log continuously.

**Comment by shamblett** [comment]
This is showing me that you are either not sending or receiving anything or the only log level you have turned on is the INFO level, check your coap_config.yaml file has enabled all debug levels -
```
# Target is none or console
logTarget: "console"
# Log levels
logError: "true"
logDebug: "true"
logWarn: "true"
logInfo: "true"
```
or enable these in the config class in your code.
When you are sending/receiving yo should see output like this -
```
D:\Development\google\dart\projects\coap>dart example\lib\src\hello_resource.dart
EXAMPLE - Sending get request to coap.me, waiting for response....
2020-10-31 09:49:16.647: SEVERE: >> BlockwiseLayer uses MaxMessageSize: 1024 and DefaultBlockSize: 512
2020-10-31 09:49:16.653: INFO: >> CoapNetworkUDP - binding to 0.0.0.0
2020-10-31 09:49:16.653: INFO: >> Starting endpoint bound to InternetAddress('134.102.218.18', IPv4)
2020-10-31 09:49:16.685: INFO: >> Reliability - Scheduling transmission for
<<< Request Message >>>
Type: 0, Code: GET, Id: 18719, Token: 000022f3,
Options =
[
If-Match :
Uri Host : Uri-Host: coap.me
E-tags :
None
Uri Port : 5683
Location Paths:
Uri Paths : hello
Content-Type : None
Max Age : None
Uri Queries :
Accept : None
Location Queries :
Proxy Uri : None
Proxy Scheme : None
Block 1 : None
Block 2 : None
Observe : -1
Size 1 : 0
Size 2 : 0
],
Payload :
null
2020-10-31 09:49:16.685: INFO: >> Reliability - sending request, failed transmission count: 0
2020-10-31 09:49:16.685: INFO: >> Reliability - Retransmission timeout is 3957 ms
2020-10-31 09:49:16.685: INFO: >> Matcher - Stored open request by KeyID[18719]) + KeyToken[000022f3]
2020-10-31 09:49:16.700: INFO: >> CoapNetworkUDP - binding to 0.0.0.0
2020-10-31 09:49:20.653: WARNING: >> Reliability - Retransmission timeout elapsed
2020-10-31 09:49:20.653: WARNING: >> Reliability - Timeout: retransmit message, failed count: 1 message: 18719
2020-10-31 09:49:20.653: INFO: >> Reliability - Scheduling transmission for
<<< Request Message >>>
Type: 0, Code: GET, Id: 18719, Token: 000022f3,
Options =
[
If-Match :
Uri Host : Uri-Host: coap.me
E-tags :
None
Uri Port : 5683
Location Paths:
Uri Paths : hello
Content-Type : None
Max Age : None
Uri Queries :
Accept : None
Location Queries :
Proxy Uri : None
Proxy Scheme : None
Block 1 : None
Block 2 : None
Observe : -1
Size 1 : 0
Size 2 : 0
],
Payload :
null
2020-10-31 09:49:20.653: INFO: >> Reliability - sending request, failed transmission count: 0
2020-10-31 09:49:20.659: INFO: >> Reliability - Retransmission timeout is 3424 ms
2020-10-31 09:49:20.659: INFO: >> Matcher - Stored open request by KeyID[18719]) + KeyToken[000022f3]
2020-10-31 09:49:20.706: INFO: >> Matcher - received response
<<< Response Message >>>
Type: 2, Code: 2.05 Content, Id: 18719, Token: 000022f3,
Options =
[
If-Match :
Uri Host : None
E-tags :
None
Uri Port : None
Location Paths:
Uri Paths :
Content-Type : 0
Max Age : None
Uri Queries :
Accept : -1
Location Queries :
Proxy Uri : None
Proxy Scheme : None
Block 1 : None
Block 2 : None
Observe : -1
Size 1 : 0
Size 2 : 0
],
Payload :
world
2020-10-31 09:49:20.721: INFO: >> Matcher - cleaning up KeyID[18719])
2020-10-31 09:49:20.721: INFO: >> Reliability - Cancel retransmission for token: 000022f3 id: 18719
EXAMPLE - response received
world
2020-10-31 09:49:20.721: INFO: >> Close - closing client
2020-10-31 09:49:20.721: INFO: >> Endpoint - stopping endpoint bound to InternetAddress('134.102.218.18', IPv4)
2020-10-31 09:49:20.721: INFO: >> Network UDP - closing coap.me, port 5683
2020-10-31 09:49:20.737: INFO: >> Stopping Mark-And-Sweep
```
Even if you are not receiving anything you should see the sends.

If you have any problems doing this on flutter I suggest you contact user @pedromassango  who added the flutter example to the client.

**Comment by anayajoshi** [comment]
how to increase payload size?
Currently I am able to send only 16 bytes payload for put request, whereas I need to send more data.
How can In achieve this?

**Comment by anayajoshi** [comment]
> This is showing me that you are either not sending or receiving anything or the only log level you have turned on is the INFO level, check your coap_config.yaml file has enabled all debug levels -
> 
> ```
> # Target is none or console
> logTarget: "console"
> # Log levels
> logError: "true"
> logDebug: "true"
> logWarn: "true"
> logInfo: "true"
> ```
> 
> or enable these in the config class in your code.
> When you are sending/receiving you should see output like this -
> 
> ```
> D:\Development\google\dart\projects\coap>dart example\lib\src\hello_resource.dart
> EXAMPLE - Sending get request to coap.me, waiting for response....
> 2020-10-31 09:49:16.647: SEVERE: >> BlockwiseLayer uses MaxMessageSize: 1024 and DefaultBlockSize: 512
> 2020-10-31 09:49:16.653: INFO: >> CoapNetworkUDP - binding to 0.0.0.0
> 2020-10-31 09:49:16.653: INFO: >> Starting endpoint bound to InternetAddress('134.102.218.18', IPv4)
> 2020-10-31 09:49:16.685: INFO: >> Reliability - Scheduling transmission for
> <<< Request Message >>>
> Type: 0, Code: GET, Id: 18719, Token: 000022f3,
> Options =
> [
> If-Match :
> Uri Host : Uri-Host: coap.me
> E-tags :
> None
> Uri Port : 5683
> Location Paths:
> Uri Paths : hello
> Content-Type : None
> Max Age : None
> Uri Queries :
> Accept : None
> Location Queries :
> Proxy Uri : None
> Proxy Scheme : None
> Block 1 : None
> Block 2 : None
> Observe : -1
> Size 1 : 0
> Size 2 : 0
> ],
> Payload :
> null
> 2020-10-31 09:49:16.685: INFO: >> Reliability - sending request, failed transmission count: 0
> 2020-10-31 09:49:16.685: INFO: >> Reliability - Retransmission timeout is 3957 ms
> 2020-10-31 09:49:16.685: INFO: >> Matcher - Stored open request by KeyID[18719]) + KeyToken[000022f3]
> 2020-10-31 09:49:16.700: INFO: >> CoapNetworkUDP - binding to 0.0.0.0
> 2020-10-31 09:49:20.653: WARNING: >> Reliability - Retransmission timeout elapsed
> 2020-10-31 09:49:20.653: WARNING: >> Reliability - Timeout: retransmit message, failed count: 1 message: 18719
> 2020-10-31 09:49:20.653: INFO: >> Reliability - Scheduling transmission for
> <<< Request Message >>>
> Type: 0, Code: GET, Id: 18719, Token: 000022f3,
> Options =
> [
> If-Match :
> Uri Host : Uri-Host: coap.me
> E-tags :
> None
> Uri Port : 5683
> Location Paths:
> Uri Paths : hello
> Content-Type : None
> Max Age : None
> Uri Queries :
> Accept : None
> Location Queries :
> Proxy Uri : None
> Proxy Scheme : None
> Block 1 : None
> Block 2 : None
> Observe : -1
> Size 1 : 0
> Size 2 : 0
> ],
> Payload :
> null
> 2020-10-31 09:49:20.653: INFO: >> Reliability - sending request, failed transmission count: 0
> 2020-10-31 09:49:20.659: INFO: >> Reliability - Retransmission timeout is 3424 ms
> 2020-10-31 09:49:20.659: INFO: >> Matcher - Stored open request by KeyID[18719]) + KeyToken[000022f3]
> 2020-10-31 09:49:20.706: INFO: >> Matcher - received response
> <<< Response Message >>>
> Type: 2, Code: 2.05 Content, Id: 18719, Token: 000022f3,
> Options =
> [
> If-Match :
> Uri Host : None
> E-tags :
> None
> Uri Port : None
> Location Paths:
> Uri Paths :
> Content-Type : 0
> Max Age : None
> Uri Queries :
> Accept : -1
> Location Queries :
> Proxy Uri : None
> Proxy Scheme : None
> Block 1 : None
> Block 2 : None
> Observe : -1
> Size 1 : 0
> Size 2 : 0
> ],
> Payload :
> world
> 2020-10-31 09:49:20.721: INFO: >> Matcher - cleaning up KeyID[18719])
> 2020-10-31 09:49:20.721: INFO: >> Reliability - Cancel retransmission for token: 000022f3 id: 18719
> EXAMPLE - response received
> world
> 2020-10-31 09:49:20.721: INFO: >> Close - closing client
> 2020-10-31 09:49:20.721: INFO: >> Endpoint - stopping endpoint bound to InternetAddress('134.102.218.18', IPv4)
> 2020-10-31 09:49:20.721: INFO: >> Network UDP - closing coap.me, port 5683
> 2020-10-31 09:49:20.737: INFO: >> Stopping Mark-And-Sweep
> ```
> 
> Even if you are not receiving anything you should see the sends.
> 
> If you have any problems doing this on flutter I suggest you contact user @pedromassango who added the flutter example to the client.

log issue solved as per your suggestion. 
Thank you so much.

**Comment by anayajoshi** [comment]
> how to increase payload size?
> Currently I am able to send only 16 bytes payload for put request, whereas I need to send more data.
> How can In achieve this?

please suggest solution on this issue.

**Comment by shamblett** [comment]
Not sure what you mean, there are many payload setting methods on the CoapMessagewhere you can set payload and media type
```
 /// Sets the payload.
  CoapMessage setPayload(String payload) { .........

/// Sets the payload of this CoAP message.
  CoapMessage setPayloadMediaRaw(typed.Uint8Buffer payload, int mediaType) { .....
```

This doesn't seem to have anything to do with this issue which from your comments above you seem to have solved so I'm closing this issue. Please raise other specific issues if you find the client is not working, also please look at all the examples in the examples directory for usage examples.. If you do find any other issues remember I will need a full log output.
